bestdevelopers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import View


# class Baz(View):
#     PASSWORD = "xyzzy"
#
#
# class Foo(Baz):
#     def get(self, request):
#         assert False, "XYZ"
#
#     def post(self, request):
#         assert False, "ABC"
#
# class Bar(Baz):
#     def get(self, request):
#         assert False, "XYZ"
#
#     def post(self, request):
#         assert False, "ABC"


# def foo(request):
#     assert False, "XXXXX"



urlpatterns = [
    # url(r'foo/', Foo.as_view()),
    url(r'^w/', include('wanted.urls', namespace="wanted")),
    url(r'^admin/', admin.site.urls),
]

wanted/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.AdListView.as_view(), name="list"),
    url(r'^api/$', views.AdJsonView.as_view(), name="api"),
    url(r'^(?P<pk>\d+)/$', views.AdDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/edit/$', views.AdUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/delete/$', views.AdDeleteView.as_view(), name="delete"),
    url(r'^add/$', views.AdCreateView.as_view(), name="add"),
    url(r'^contact/$', views.ContactUsView.as_view(), name="contact"),
]

wanted/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.six import python_2_unicode_compatible


class Category(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    priority = models.IntegerField(default=10)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


class Ad(models.Model):
    category = models.ForeignKey(Category)
    created_at = models.DateTimeField(auto_now_add=True,
                                      db_index=True)
    title = models.CharField(max_length=500)
    description = models.TextField()
    contact_person = models.CharField(max_length=100)
    apply_email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)

    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("wanted:detail", args=(self.id,))

wanted/forms.py
from django import forms

from . import models


class ContactUsForm(forms.Form):
    subject = forms.CharField(max_length=200)
    content = forms.CharField(max_length=1000,
                              widget=forms.Textarea())
    email = forms.EmailField()
    is_important = forms.BooleanField()


class AdForm(forms.ModelForm):
    class Meta:
        model = models.Ad
        exclude = ()

wanted/views.py
from django.core.urlresolvers import reverse_lazy
from django.http.response import JsonResponse
from django.views.generic import FormView
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from wanted import forms
from . import models


class AdMixin:
    model = models.Ad
    title = "HELLO WORLD!"


    def get_context_data(self, **kwargs):
        d = super().get_context_data(**kwargs)
        d['foo'] = 1234
        return d


class AdListView(AdMixin, ListView):
    paginate_by = 10

class AdJsonView(View):
    def get(self, request):
        qs = models.Ad.objects.all()
        return JsonResponse({'data':[
            {'id': o.id, 'title': o.title} for o in qs
        ]})

class AdDetailView(AdMixin, DetailView):
    pass


class AdCreateView(AdMixin, CreateView):
    form_class = forms.AdForm


class AdUpdateView(AdMixin, UpdateView):
    form_class = forms.AdForm


class AdDeleteView(AdMixin, DeleteView):
    success_url = reverse_lazy("wanted:list")


class ContactUsView(FormView):
    template_name = "contact_us.html"
    form_class = forms.ContactUsForm
    success_url = reverse_lazy("wanted:list")

    def form_valid(self, form):
        # mail.send_email(form.cleaned_data)
        return super().form_valid(form)

wanted/templates/ad_detail.html
<a href="{% url "wanted:list" %}">Back to list</a>

<h1>{{ object.title }}</h1>

<i>{{ object.created_at }}</i>

<p>
    {{ object.description|linebreaksbr }}
</p>

{% lorem %}

wanted/templates/contact_us.html
<form method="post">
    {% csrf_token %}
    <ul>
        {{ form.as_ul }}
        <button>Send</button>
    </ul>
</form>

wanted/templates/wanted/ad_confirm_delete.html
Are you sure you want to delete {{ object }}?
<form method="post">
    {% csrf_token %}
    <ul>
        {{ form.as_ul }}
        <button>Delete</button>
    </ul>
</form>

wanted/templates/wanted/ad_detail.html
<a href="{% url "wanted:list" %}">Back to list</a>

<h1>{{ object.title }}</h1>

<i>{{ object.created_at }}</i>

<p>
    {{ object.description|linebreaksbr }}
</p>

<a href="{% url "wanted:update" object.id %}">Edit</a>
<br>
<a href="{% url "wanted:delete" object.id %}">Delete</a>


<br>
<br>
{{ view.title }}
<br>
{{ foo }}

wanted/templates/wanted/ad_form.html
<form method="post">
    {% csrf_token %}
    <ul>
        {{ form.as_ul }}
        <button>Add</button>
    </ul>
</form>

wanted/templates/wanted/ad_list.html
{% load humanize %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link rel="stylesheet"
          href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="container">

    <h1>
        Wanted!
    </h1>

    <ul class="list-group">
        {% for object in object_list %}
            <li class="list-group-item">
                <a href="{{ object.get_absolute_url }}">
                    {{ object }}
                </a>
                ({{ object.created_at|naturaltime }})
                &nbsp;
                {% if object.apply_email %}
                    <a href="mailto:{{ object.apply_email }}">
                        <i class="glyphicon glyphicon-envelope"></i>
                    </a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

</div>

</body>